### ISSUE TITLE
Reporte de objeto de diseño 3D en Blender_Edwin, Iván, Taoli, Alexis

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo_cafe-huerto-el-mamey#2]
[Reporte de Blender.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo_cafe-huerto-el-mamey/files/8228915/Reporte.de.Blender.pdf)

**Comment by Jaci14** [comment]
Contiene todos los elementos que se pide en la practica y son congruentes con la descripción de la practica.

Puntos: 100
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
